# Generated by Django 5.1.2 on 2025-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='title_work',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
