# Generated by Django 5.1.2 on 2025-02-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Urls_to_social_network',
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterField(
            model_name='consultation',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
