# Generated by Django 5.1.2 on 2025-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0002_delete_urls_to_social_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls_to_social_network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('urls', models.URLField(blank=True, null=True, verbose_name='Ссылка на соцсеть')),
                ('name_social', models.CharField(blank=True, null=True, verbose_name='Название соц сети')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Ссылки на соц сети Navis Devs',
                'verbose_name_plural': 'Ссылки на соц сети Navis Devs',
            },
        ),
    ]
