# Generated by Django 5.1.2 on 2025-01-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0002_vacancy_title_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='img',
        ),
    ]
