# Generated by Django 5.1.2 on 2025-01-28 10:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0003_remove_services_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
