# Generated by Django 5.1.2 on 2025-02-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0003_urls_to_social_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('other', 'Other')], default='other', max_length=5)),
            ],
        ),
    ]
