# Generated by Django 5.1.2 on 2025-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': 'Презинтация', 'verbose_name_plural': 'Презинтация'},
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='media', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('other', 'Other')], default='other', max_length=5, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время добовление'),
        ),
    ]
