# Generated by Django 5.1.2 on 2025-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0004_vacancy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='job_title',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Fullstack', 'Fullstack')], max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_work',
            field=models.CharField(max_length=255, verbose_name='Описание работы'),
        ),
    ]
