# Generated by Django 5.1.2 on 2025-01-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0005_alter_vacancy_job_title_alter_vacancy_title_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title_work',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='working_conditions',
        ),
    ]
