# Generated by Django 5.1.2 on 2025-02-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0005_alter_uploadedfile_options_alter_uploadedfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='services',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tools',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='language',
            field=models.CharField(choices=[('ru', 'Rus'), ('en', 'ENG')], max_length=10),
        ),
    ]
