# Generated by Django 5.1.2 on 2025-01-29 09:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0006_remove_vacancy_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='services',
            name='additionUI',
        ),
        migrations.RemoveField(
            model_name='services',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='services',
            name='design',
        ),
        migrations.RemoveField(
            model_name='services',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='services',
            name='img_additionUI',
        ),
        migrations.RemoveField(
            model_name='services',
            name='img_framework',
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
