# Generated by Django 5.1.2 on 2025-01-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0007_remove_event_requirements_remove_services_additionui_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navis.aboutus', verbose_name='О нас')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navis.contacts', verbose_name='Контакты')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navis.projects', verbose_name='Проекты')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navis.reviews', verbose_name='Отзывы')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navis.vacancy', verbose_name='Вакансии')),
            ],
        ),
    ]
