# Generated by Django 5.1.2 on 2025-01-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0008_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
    ]
