# Generated by Django 5.1.2 on 2025-01-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Время добавление'),
        ),
    ]
