# Generated by Django 5.1.2 on 2025-01-29 14:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0010_alter_services_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='industry',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Отрасль'),
        ),
    ]
