# Generated by Django 5.1.2 on 2025-01-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0011_alter_services_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(verbose_name='Видио из Youtube')),
            ],
        ),
    ]
