# Generated by Django 5.1.2 on 2025-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0012_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
