# Generated by Django 5.1.2 on 2025-01-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0013_reviews_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(verbose_name='Видио')),
            ],
        ),
        migrations.DeleteModel(
            name='Youtube',
        ),
    ]
