# Generated by Django 5.1.2 on 2025-01-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0014_video_delete_youtube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видио', 'verbose_name_plural': 'Видио'},
        ),
    ]
