# Generated by Django 5.1.2 on 2025-01-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0015_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видeo', 'verbose_name_plural': 'Видeo'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_work',
            field=models.CharField(default=1, max_length=255, verbose_name='Опимсание работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='urls',
            field=models.URLField(verbose_name='Видeo'),
        ),
    ]
