# Generated by Django 5.1.2 on 2025-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0016_alter_video_options_vacancy_title_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='title_work',
            field=models.CharField(max_length=255, verbose_name='Описание работы'),
        ),
    ]
