# Generated by Django 5.1.2 on 2025-01-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0017_alter_vacancy_title_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
