# Generated by Django 5.1.2 on 2025-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0018_alter_consultation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='message',
            field=models.CharField(default=1, max_length=255, verbose_name='Что вас интересует'),
            preserve_default=False,
        ),
    ]
