# Generated by Django 5.1.2 on 2025-01-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0019_consultation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='language',
            field=models.CharField(blank=True, choices=[('Russian', 'Rus'), ('English', 'ENG')], max_length=10, null=True),
        ),
    ]
