# Generated by Django 5.1.2 on 2025-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0020_alter_consultation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Что вас интересует'),
        ),
    ]
