# Generated by Django 5.1.2 on 2025-01-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0021_alter_consultation_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={},
        ),
        migrations.AlterField(
            model_name='consultation',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='language',
            field=models.CharField(choices=[('Russian', 'Rus'), ('English', 'ENG')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='message',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phone_number',
            field=models.CharField(default='+996', max_length=20),
        ),
    ]
