# Generated by Django 5.1.2 on 2025-01-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0022_alter_consultation_options_alter_consultation_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
