# Generated by Django 5.1.2 on 2025-01-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0023_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультация'},
        ),
    ]
