# Generated by Django 5.1.2 on 2025-01-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0024_alter_consultation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='job_title',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Fullstack', 'Fullstack'), ('test', 'test')], max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('test', 'test')], max_length=255, verbose_name='Уровень'),
        ),
    ]
